import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, extname, resolve } from "node:path";
import type { LoydSchema } from "@loydjs/core";
import { generateCode } from "../jit/codegen.js";
import { optimize } from "../jit/optimizer.js";

export interface EmitOptions {
  outFile: string;
  exportName?: string;
  format?: "esm" | "cjs";
  dts?: boolean;
}

export interface EmitResult {
  jsFile: string;
  dtsFile?: string;
  bytes: number;
}

function generateEmitCode(
  schema: LoydSchema<unknown>,
  exportName: string,
  format: "esm" | "cjs",
): string {
  const { schema: optimized } = optimize(schema);
  const { code, fnName, schemaRefs } = generateCode(optimized, {
    mode: "production",
    fnName: `__loyd_${exportName}__`,
  });

  const hasRefs = Object.keys(schemaRefs).length > 0;

  const schemaRefsCode = hasRefs ? buildSchemaRefsCode(schemaRefs, format) : "";

  const validatorBody = hasRefs
    ? `${code}\nconst __schemas__ = ${buildSchemasRegistryCode(schemaRefs)};\nreturn ${fnName};`
    : `${code}\nreturn ${fnName};`;

  const validatorFn = `(function() {\n  "use strict";\n  ${validatorBody.split("\n").join("\n  ")}\n})()`;

  if (format === "esm") {
    return [
      "// Generated by @loydjs/compiler - do not edit",
      `// Schema: ${schema._type}`,
      "",
      schemaRefsCode,
      `export const ${exportName} = ${validatorFn};`,
      "",
      `export default ${exportName};`,
      "",
    ]
      .filter((l) => l !== undefined)
      .join("\n");
  }

  // CJS
  return [
    `"use strict";`,
    "// Generated by @loydjs/compiler - do not edit",
    `// Schema: ${schema._type}`,
    "",
    schemaRefsCode,
    `const ${exportName} = ${validatorFn};`,
    "",
    `module.exports = ${exportName};`,
    `module.exports.${exportName} = ${exportName};`,
    `module.exports.default = ${exportName};`,
    "",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}

function buildSchemaRefsCode(
  schemaRefs: Record<string, LoydSchema<unknown>>,
  _format: "esm" | "cjs",
): string {
  const parts: string[] = [];

  for (const [id, schema] of Object.entries(schemaRefs)) {
    if (id === "__schema_ref__") continue;

    const { code, fnName } = generateCode(schema, {
      mode: "production",
      fnName: `__ref_${id.replace(/[^a-z0-9]/gi, "_")}__`,
    });
    parts.push(`// Delegated schema ref: ${id} (${schema._type})`);
    parts.push(code);
    parts.push(`const ${id}_fn = ${fnName};`);
  }

  return parts.join("\n");
}

function buildSchemasRegistryCode(schemaRefs: Record<string, LoydSchema<unknown>>): string {
  const entries = Object.entries(schemaRefs)
    .filter(([id]) => id !== "__schema_ref__")
    .map(([id]) => {
      return `  ${JSON.stringify(id)}: { safeParse: ${id}_fn }`;
    });

  return `{\n${entries.join(",\n")}\n}`;
}

//.d.ts file

function generateDts(exportName: string): string {
  return [
    "// Generated by @loydjs/compiler - do not edit",
    "",
    "export interface LoydResult<T> {",
    "  success: boolean;",
    "  data: T | undefined;",
    "  issues: Array<{ code: string; path: ReadonlyArray<string | number>; message?: string; meta?: Record<string, unknown> }>;",
    "}",
    "",
    `export declare const ${exportName}: (input: unknown) => LoydResult<unknown>;`,
    `export default ${exportName};`,
    "",
  ].join("\n");
}

export async function emit(schema: LoydSchema<unknown>, options: EmitOptions): Promise<EmitResult> {
  const {
    outFile,
    exportName = basename(outFile, extname(outFile)),
    format = "esm",
    dts = false,
  } = options;

  const resolvedOut = resolve(outFile);
  const outDir = dirname(resolvedOut);

  await mkdir(outDir, { recursive: true });

  const jsCode = generateEmitCode(schema, exportName, format);
  await writeFile(resolvedOut, jsCode, "utf8");

  let dtsFile: string | undefined;

  if (dts) {
    const dtsCode = generateDts(exportName);
    dtsFile = resolvedOut.replace(/\.(js|mjs|cjs)$/, ".d.ts");
    await writeFile(dtsFile, dtsCode, "utf8");
  }

  return {
    jsFile: resolvedOut,
    dtsFile,
    bytes: Buffer.byteLength(jsCode, "utf8"),
  };
}
